# fly.toml - Configuration Fly.io pour Telemed
app = "telemed-prod"
primary_region = "cdg"  # Paris - Changez selon votre région préférée

[build]

[deploy]
  release_command = "/app/bin/telemed eval 'Telemed.Release.migrate'"

[env]
  PHX_HOST = "telemed-prod.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/priv/static"
  url_prefix = "/"

